### ISSUE TITLE
The Source Code | Issue links in the bottom of the app are wrong 

### ISSUE THREAD

**Issue by yyfearth** [ahmadnassri/app-restconsole#80]
The Source Code and Issue links in the bottom of the app are link to
`https://github.com/codeinchaos/rest-console` which should be `https://github.com/codeinchaos/restconsole`

**Comment by gregmac** [comment]
Was fixed in fe7ebac

**Comment by pv7721** [comment]
How come people still see it and keep reporting it over and over?!?

**Comment by ahmadnassri** [comment]
@pv7721 because a newer version was not released to the store yet.
